### ISSUE TITLE
Installation method fails

### ISSUE THREAD

**Issue by jvijay-work** [40ants/lem-pareto#1]
COMPILE-FILE-ERROR while
     ling #<CL-SOURCE-FILE "lem-pareto/lem-pareto-mode" "lisp">
     race for: #<SB-THREAD:THREAD "editor" RUNNING {10038AB7E3}>
     LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
     FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX)
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE) {10057DA
4: (LEM:POP-UP-BACKTRACE #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10057D8753}>)
5: ((FLET "H0" :IN LEM::TOPLEVEL-COMMAND-LOOP) #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10057D8753}>)
6: (SB-KERNEL::%SIGNAL #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10057D8753}>)
7: (ERROR UIOP/LISP-BUILD:COMPILE-FILE-ERROR :CONTEXT-FORMAT "~/asdf-action::format-action/" :CONTEXT-AR
8: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACT
9: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-O
10: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
11: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LI
12: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {10048FA0C3}>) [fast-method]
13: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
14: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {10048FA0C3}>) [fast-metho
15: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTI
16: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP
17: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
18: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/PACKAGE-INFERRED-S
19: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP :
20: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
21: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :LEM-PARETO) [fast-method]
22: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {10048F274B}>
__________________________________________________ Top _________________________________________________

**Comment by svetlyak40wt** [comment]
Probably LEM has changed since last time I was using it with this plugin. Right now I'm not using LEM. Please, try to debug and fix this issue and send a pull-request.

**Comment by cxxxr** [comment]
@svetlyak40wt I think this issue has been resolved by #2.
